print("exercici2.1")
print("1", "2", "3", "4", "5", sep="---", end="++\n")
print("1--2--3--4--5++")
print("Exercici2.2")
print("\"Estoy\"")
print("\"'Algunos símbolos'\"")
print("\"''Son difíciles de imprimir: '/'\" ''\"")
print("I'm a programmer!!")
print("exercici2.3")
print("I'm Monty Python.")
print("(3+2), 2·5):")